travis:
  secure:
    BINSTAR_TOKEN: XN2EjGROvldKwBohc3cWCDfZ7qCQw4TqqYYxJ3NE49eT6gnaG0M9E7nMBTnWtrDFdz9MUUHjZMe+CsnrPr1yBu6kAqdzsddOMW0dlc8IQ2/ldyxG7JyLG6YIZl0I2F4G6muznKJ7wUe6+nUqOsCIN7bkHyMQvyYc9LVXETubNGrAJkYlcml+T+RTT5GG+HunoJ1fK7fKJEbGttqt4hbtLRuXOEtHDAsElYCIi2+AqjagujqZR9MVvbFU64wakH0gAu+Gl8NTJnwJgWrwM82REGfVWIaJxUJ5eiW9DD9Y4DFjVcxQR9C5OKy2DgIJviaIboQHPKrTBO+ps3vBNqBllwjkbQTn9s1QwJ6qEUVTy9brw2TnzA9klZ/JmqOj7NYpOYkD07JV08/7+yV1jf7aJFYY1JR1OpEgDMQZnvpqU0u9EzSHhaBh+MbC1WKdOXbd2028Yb9uqXYBEVz/ASytGgtVTfm6+6utMzHR/wVl/WaQX3JYMpbMOXslRKgZZOV5a7u4/PGfB9Gz4CMRSJPYLjZm1tlfhC4ykBszd0HiE2/e/XD4VOl4rNdlIx0azJ24Vo+Cl4fMWJjzhi+ZDFLC8tzSLEHtdRIbkdQ3McTpUSOh3aYSSaZTGhvnyk3F+iSXYK7x8aD26DqULv3KL1pQ8Ml2XTJUrZG8McvdUQ1gHc4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
